name       : mdds
version    : 1.4.3
release    : 5
source     :
    - https://gitlab.com/mdds/mdds/-/archive/1.4.3/mdds-1.4.3.tar.bz2 : 13aec009e3cf024f083b30c52ed5e3f8c349a25c79bd0e261c5e8b7f70280406
license    : MIT
component  : programming.library
summary    : Multi-Dimensional Data Structure
description: |
    A collection of multi-dimensional data structure and indexing algorithm.
patterns   :
    - /usr/include/mdds*
builddeps  :
    - libboost-devel # check
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
