name       : mdds
version    : 1.3.1
release    : 3
source     :
    - https://kohei.us/files/mdds/src/mdds-1.3.1.tar.bz2 : dcb8cd2425567a5a5ec164afea475bce57784bca3e352ad4cbdd3d1a7e08e5a1
license    : MIT
component  : programming
summary    : Multi-Dimensional Data Structure
description: |
    A collection of multi-dimensional data structure and indexing algorithm.
patterns   :
    - /usr/include/mdds*
builddeps  :
    - libboost-devel # check
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
