name       : mdds
version    : 1.3.1
release    : 4
source     :
    - https://gitlab.com/mdds/mdds/-/archive/1.3.1/mdds-1.3.1.tar.bz2 : 282b060d0bd67849b3b0c635d892d1eb0a21f5bdf4994e5ea1e0b9d445e5da3c
license    : MIT
component  : programming.library
summary    : Multi-Dimensional Data Structure
description: |
    A collection of multi-dimensional data structure and indexing algorithm.
patterns   :
    - /usr/include/mdds*
builddeps  :
    - libboost-devel # check
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
