name       : mdds
version    : 2.1.1
release    : 10
source     :
    - https://gitlab.com/mdds/mdds/-/archive/2.1.1/mdds-2.1.1.tar.gz : 4b9b4ef83826562a57d55089141c8d59789fae829fd6402cbb95d480c0737b7d
homepage   : https://gitlab.com/mdds/mdds
license    : MIT
component  : programming.library
summary    : Multi-Dimensional Data Structure
description: |
    A collection of multi-dimensional data structure and indexing algorithm.
patterns   :
    - /usr/include/mdds*
builddeps  :
    - libboost-devel # check
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
check      : |
    %make check
