name       : mdds
version    : 1.5.0
release    : 6
source     :
    - https://gitlab.com/mdds/mdds/-/archive/1.5.0/mdds-1.5.0.tar.bz2 : 6193885e453d03f7d30c8d65c1ee917154eab410d85d138709a27fab3fc3e011
license    : MIT
component  : programming.library
summary    : Multi-Dimensional Data Structure
description: |
    A collection of multi-dimensional data structure and indexing algorithm.
patterns   :
    - /usr/include/mdds*
builddeps  :
    - libboost-devel # check
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
