name       : mdds
version    : 2.0.3
release    : 9
source     :
    - https://gitlab.com/mdds/mdds/-/archive/2.0.3/mdds-2.0.3.tar.gz : 5d6dae6e1650685e62f744a2cc4d60257a286b97447cec07261720410c30d990
license    : MIT
component  : programming.library
summary    : Multi-Dimensional Data Structure
description: |
    A collection of multi-dimensional data structure and indexing algorithm.
patterns   :
    - /usr/include/mdds*
builddeps  :
    - libboost-devel # check
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
check      : |
    %make check
