name       : mdds
version    : 1.6.0
release    : 7
source     :
    - https://gitlab.com/mdds/mdds/-/archive/1.6.0/mdds-1.6.0.tar.bz2 : f843ffe3964d812effe8ea58ba4672ca74333fdf3bc158ed9972dc4dd985a35d
license    : MIT
component  : programming.library
summary    : Multi-Dimensional Data Structure
description: |
    A collection of multi-dimensional data structure and indexing algorithm.
patterns   :
    - /usr/include/mdds*
builddeps  :
    - libboost-devel # check
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
