name       : mdds
version    : 1.2.3
release    : 2
source     :
    - http://kohei.us/files/mdds/src/mdds-1.2.3.tar.bz2 : 402fec18256f95b89517d54d85f00bce1faa6e517cb3d7c98a720fddd063354f
license    : MIT
component  : programming
patterns   :
    - /usr/include/mdds*
summary    : A collection of multi-dimensional data structure and indexing algorithm
description: |
    A collection of multi-dimensional data structure and indexing algorithm.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
