name       : mdds
version    : 2.0.1
release    : 8
source     :
    - https://gitlab.com/mdds/mdds/-/archive/2.0.1/mdds-2.0.1.tar.gz : 4a71007ad606510fcf10c1f48e4bcff8a9ea43f40fcb99015b76681131e331c1
license    : MIT
component  : programming.library
summary    : Multi-Dimensional Data Structure
description: |
    A collection of multi-dimensional data structure and indexing algorithm.
patterns   :
    - /usr/include/mdds*
builddeps  :
    - libboost-devel # check
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
