name       : mdds
version    : 1.2.2
release    : 1
source     :
    - http://kohei.us/files/mdds/src/mdds-1.2.2.tar.bz2 : 141e730b39110434b02cd844c5ad3442103f7c35f7e9a4d6a9f8af813594cc9d
license    : MIT
component  : programming
patterns   :
    - /usr/include/mdds*
summary    : A collection of multi-dimensional data structure and indexing algorithm
description: |
    A collection of multi-dimensional data structure and indexing algorithm.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
